#!/bin/bash




# -------- DEFINITIONS --------

#exit on error
set -e

#current executable directory
CXD=$(dirname $(readlink -f $0))
pCXD=$(dirname $CXD)

#paths
SRC=$pCXD/src
OUT=$pCXD/out
TMP=$OUT/tmp






# -------- PREPARE ENVIRONMENT --------

#clean
$CXD/clean

#remove previous blds
rm --force $OUT/obj-to-elf.elf

#tmp dir
[[ ! -d $TMP ]] && mkdir --parents $TMP






# -------- EXECUTION --------

#copy as if it was a real ELF build
cp $SRC/obj-to-elf.py $OUT/obj-to-elf.elf
